/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as NegociosRouteImport } from './routes/negocios'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PaqueteIdRouteImport } from './routes/paquete.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosRoute = NegociosRouteImport.update({
  id: '/negocios',
  path: '/negocios',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaqueteIdRoute = PaqueteIdRouteImport.update({
  id: '/paquete/$id',
  path: '/paquete/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/negocios': typeof NegociosRoute
  '/panel': typeof PanelRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/negocios': typeof NegociosRoute
  '/panel': typeof PanelRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/negocios': typeof NegociosRoute
  '/panel': typeof PanelRoute
  '/paquete/$id': typeof PaqueteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explorar'
    | '/mis-pedidos'
    | '/negocios'
    | '/panel'
    | '/paquete/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explorar'
    | '/mis-pedidos'
    | '/negocios'
    | '/panel'
    | '/paquete/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explorar'
    | '/mis-pedidos'
    | '/negocios'
    | '/panel'
    | '/paquete/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExplorarRoute: typeof ExplorarRoute
  MisPedidosRoute: typeof MisPedidosRoute
  NegociosRoute: typeof NegociosRoute
  PanelRoute: typeof PanelRoute
  PaqueteIdRoute: typeof PaqueteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios': {
      id: '/negocios'
      path: '/negocios'
      fullPath: '/negocios'
      preLoaderRoute: typeof NegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paquete/$id': {
      id: '/paquete/$id'
      path: '/paquete/$id'
      fullPath: '/paquete/$id'
      preLoaderRoute: typeof PaqueteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExplorarRoute: ExplorarRoute,
  MisPedidosRoute: MisPedidosRoute,
  NegociosRoute: NegociosRoute,
  PanelRoute: PanelRoute,
  PaqueteIdRoute: PaqueteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
